// ─────────────────────────────────────────────────────────────────────────────
// src/regions.js  —  LocalBiz GH · All 16 Ghana Regions + Districts
// Source: Official Ghana Districts Excel Data
// ─────────────────────────────────────────────────────────────────────────────

export const GHANA_REGIONS = [
  {
    region: "Greater Accra Region",
    districts: [
      "Accra Metropolitan",
      "Tema Metropolitan",
      "Adentan Municipal",
      "Ashaiman Municipal",
      "Ga Central Municipal",
      "Ga East Municipal",
      "Ga North Municipal",
      "Ga South Municipal",
      "Ga West Municipal",
      "La Dade Kotopon Municipal",
      "La Nkwantanang–Madina Municipal",
      "Ledzokuku Municipal",
      "Kpone Katamanso Municipal",
      "Ningo Prampram District",
      "Ada East District",
      "Ada West District",
      "Shai Osudoku District",
      "Ablekuma North Municipal",
      "Ablekuma West Municipal",
      "Ayawaso East Municipal",
      "Ayawaso North Municipal",
      "Ayawaso West Municipal",
      "Okaikwei North Municipal",
      "Korle Klottey Municipal",
      "Krowor Municipal",
      "Weija Gbawe Municipal",
      "Tema West Municipal",
      "Ablekuma Central Municipal",
      "Ablekuma South Municipal",
    ],
  },
  {
    region: "Ashanti Region",
    districts: [
      "Kumasi Metropolitan",
      "Asokore Mampong Municipal",
      "Obuasi Municipal",
      "Ejisu Municipal",
      "Asante Akim North",
      "Asante Akim South",
      "Bosome Freho",
      "Bosomtwe",
      "Afigya Kwabre North",
      "Afigya Kwabre South",
      "Sekyere East",
      "Sekyere South",
      "Sekyere Afram Plains",
      "Sekyere Kumawu",
      "Atwima Mponua",
      "Atwima Nwabiagya North",
      "Atwima Nwabiagya South",
      "Atwima Kwanwoma",
      "Amansie Central",
      "Amansie West",
      "Amansie South",
      "Adansi Asokwa",
      "Adansi North",
      "Adansi South",
      "Offinso Municipal",
      "Offinso North",
      "Kwabre East",
      "Asante Akim Central",
      "Mampong Municipal",
      "Ejura Sekyedumase",
    ],
  },
  {
    region: "Eastern Region",
    districts: [
      "New Juaben South Municipal",
      "New Juaben North Municipal",
      "Akuapem North Municipal",
      "Akuapem South Municipal",
      "Akyemansa District",
      "Atiwa East District",
      "Atiwa West District",
      "Birim Central Municipal",
      "Birim North District",
      "Birim South District",
      "Denkyembour District",
      "Fanteakwa North",
      "Fanteakwa South",
      "Kwahu Afram Plains North",
      "Kwahu Afram Plains South",
      "Kwahu East",
      "Kwahu South",
      "Kwahu West",
      "Lower Manya Krobo",
      "Upper Manya Krobo",
      "Okere District",
      "Suhum Municipal",
      "Abuakwa South",
      "Abuakwa North",
      "West Akim Municipal",
      "Upper West Akim",
    ],
  },
  {
    region: "Central Region",
    districts: [
      "Cape Coast Metropolitan",
      "Komenda Edina Eguafo Abrem",
      "Abura Asebu Kwamankese",
      "Agona East",
      "Agona West Municipal",
      "Ajumako Enyan Essiam",
      "Asikuma Odoben Brakwa",
      "Assin Central Municipal",
      "Assin North",
      "Assin South",
      "Awutu Senya East Municipal",
      "Awutu Senya West",
      "Ekumfi",
      "Effutu Municipal",
      "Gomoa East",
      "Gomoa Central",
      "Gomoa West",
      "Mfantseman Municipal",
      "Twifo Atti Morkwa",
      "Twifo Hemang Lower Denkyira",
      "Upper Denkyira East Municipal",
      "Upper Denkyira West",
    ],
  },
  {
    region: "Western Region",
    districts: [
      "Sekondi Takoradi Metropolitan",
      "Effia Kwesimintsim Municipal",
      "Shama District",
      "Wassa East",
      "Wassa Amenfi East",
      "Wassa Amenfi Central",
      "Wassa Amenfi West",
      "Ellembelle",
      "Jomoro",
      "Nzema East Municipal",
      "Ahanta West",
      "Mpohor",
      "Tarkwa Nsuaem Municipal",
      "Prestea Huni Valley",
    ],
  },
  {
    region: "Western North Region",
    districts: [
      "Sefwi Wiawso Municipal",
      "Bia West",
      "Bia East",
      "Bibiani Anhwiaso Bekwai Municipal",
      "Aowin Municipal",
      "Suaman District",
      "Juaboso District",
      "Bodi District",
      "Akontombra District",
    ],
  },
  {
    region: "Volta Region",
    districts: [
      "Ho Municipal",
      "Ho West",
      "Adaklu",
      "Agotime Ziope",
      "Akatsi North",
      "Akatsi South",
      "Anloga",
      "Central Tongu",
      "Ketu North Municipal",
      "Ketu South Municipal",
      "North Tongu",
      "South Tongu",
      "Kpando Municipal",
      "Afadzato South",
      "Hohoe Municipal",
      "Biakoye",
      "Jasikan",
      "Kadjebi",
    ],
  },
  {
    region: "Oti Region",
    districts: [
      "Jasikan",
      "Kadjebi",
      "Krachi East Municipal",
      "Krachi West",
      "Krachi Nchumuru",
      "Nkwanta South Municipal",
      "Nkwanta North",
      "Guan District",
      "Biakoye",
    ],
  },
  {
    region: "Northern Region",
    districts: [
      "Tamale Metropolitan",
      "Sagnarigu Municipal",
      "Yendi Municipal",
      "Savelugu Municipal",
      "Kumbungu",
      "Tolon",
      "Nanton",
      "Karaga",
      "Gushegu Municipal",
      "Saboba",
      "Tatale Sanguli",
      "Mion",
      "Nanumba North Municipal",
      "Nanumba South",
    ],
  },
  {
    region: "Savannah Region",
    districts: [
      "Damongo Municipal",
      "Bole Municipal",
      "Sawla Tuna Kalba",
      "Central Gonja",
      "East Gonja Municipal",
      "North Gonja",
      "West Gonja",
    ],
  },
  {
    region: "North East Region",
    districts: [
      "Nalerigu-Gambaga Municipal",
      "Bunkpurugu-Nyankpanduri",
      "Chereponi",
      "East Mamprusi Municipal",
      "West Mamprusi Municipal",
      "Yunyoo-Nasuan",
    ],
  },
  {
    region: "Upper East Region",
    districts: [
      "Bolgatanga Municipal",
      "Bawku Municipal",
      "Bawku West",
      "Binduri",
      "Bongo",
      "Garu",
      "Kassena-Nankana Municipal",
      "Kassena-Nankana West",
      "Nabdam",
      "Pusiga",
      "Talensi",
      "Tempane",
      "Builsa North",
      "Builsa South",
      "Bolgatanga East",
    ],
  },
  {
    region: "Upper West Region",
    districts: [
      "Wa Municipal",
      "Wa East",
      "Wa West",
      "Daffiama Bussie Issa",
      "Jirapa Municipal",
      "Lambussie",
      "Lawra Municipal",
      "Nadowli Kaleo",
      "Nandom Municipal",
      "Sissala East Municipal",
      "Sissala West",
    ],
  },
  {
    region: "Bono Region",
    districts: [
      "Sunyani Municipal",
      "Sunyani West",
      "Berekum Municipal",
      "Dormaa Central Municipal",
      "Dormaa East",
      "Dormaa West",
      "Jaman North",
      "Jaman South",
      "Tain",
      "Banda",
      "Wenchi Municipal",
      "Berekum West",
    ],
  },
  {
    region: "Bono East Region",
    districts: [
      "Techiman Municipal",
      "Techiman North",
      "Atebubu Amantin Municipal",
      "Sene East",
      "Sene West",
      "Kintampo North Municipal",
      "Kintampo South",
      "Nkoranza North",
      "Nkoranza South Municipal",
      "Pru East",
      "Pru West",
    ],
  },
  {
    region: "Ahafo Region",
    districts: [
      "Goaso Municipal",
      "Asunafo North Municipal",
      "Asunafo South District",
      "Asutifi North District",
      "Asutifi South District",
      "Tano North Municipal",
    ],
  },
];

export const REGION_NAMES = GHANA_REGIONS.map(r => r.region);

export function getDistricts(regionName) {
  const found = GHANA_REGIONS.find(r => r.region === regionName);
  return found ? found.districts : [];
}

export const BUSINESS_CATEGORIES = [
  "Food & Restaurants",
  "Groceries & Supermarkets",
  "Fashion & Clothing",
  "Electronics & Gadgets",
  "Pharmacy & Health",
  "Beauty & Cosmetics",
  "Hardware & Building",
  "Agriculture & Farming",
  "Logistics & Courier",
  "Education & Tutoring",
  "Auto Parts & Services",
  "Furniture & Home Decor",
  "Printing & Stationery",
  "Events & Entertainment",
  "Hotels & Accommodation",
  "Other (specify)",
];
